name: Setup testoperator
description: 'composite action'
inputs:
  query_set:
    description: 'Query set'
    required: true
    default: 'tpch'
    type: choice
    options:
      - 'tpch'
      - 'tpch[parameterized]'
      - 'tpcds'
      - 'clickbench'

runs:
  using: 'composite'
  steps:
    - name: Prepare file-based data directory
      shell: bash
      run: |
        rm -rf /opt/spiced/data
        mkdir -p /opt/spiced/data

    - name: Download TPCH Data
      shell: bash
      if: inputs.query_set == 'tpch' || inputs.query_set == 'tpch[parameterized]'
      run: |
        cd /opt/spiced/data
        mkdir ./tpch_sf1
        mc cp spice-minio/benchmarks/tpch_sf1/ ./tpch_sf1/ --recursive
    
    - name: Download TPCDS Data
      shell: bash
      if: inputs.query_set == 'tpcds'
      run: |
        cd /opt/spiced/data
        mkdir ./tpcds_sf1
        mc cp spice-minio/benchmarks/tpcds_sf1/ ./tpcds_sf1/ --recursive
        mkdir ./sf0_01
        mc cp spice-minio/benchmarks/tpcds_sf0_01/ ./sf0_01/ --recursive
    
    - name: Download File Connector ClickBench Data
      shell: bash
      if: inputs.query_set == 'clickbench'
      run: |
        cd /opt/spiced/data
        mc cp spice-minio/benchmarks/clickbench/hits_0.parquet ./
        mc cp spice-minio/benchmarks/clickbench/hits.parquet ./