name: Setup testoperator
description: 'composite action'

# Builds the testoperator if it doesn't exist in MinIO
# Downloads it based on the commit from the HEAD of the current branch
# Uploads the testoperator binary to MinIO if built
#
# Requires the MinIO CLI to be installed and configured to use this action
inputs:
  target_os:
    description: 'OS'
    required: true
    default: 'linux'
    type: string
runs:
  using: 'composite'
  steps:
    - name: Set testoperator commit
      shell: bash
      run: |
        echo "TESTOPERATOR_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Set target binary
      if: ${{ inputs.target_os == 'linux' }}
      shell: bash
      run: |
        echo "TARGET_BINARY=linux-x86_64" >> $GITHUB_ENV
    
    - name: Set target binary
      if: ${{ inputs.target_os == 'darwin' }}
      shell: bash
      run: |
        echo "TARGET_BINARY=darwin-aarch_64" >> $GITHUB_ENV

    - name: Download the testoperator from MinIO if it exists
      shell: bash
      run: |
        if mc stat spice-minio/artifacts/testoperator/$TARGET_BINARY/$TESTOPERATOR_COMMIT/testoperator; then
          mc cp spice-minio/artifacts/testoperator/$TARGET_BINARY/$TESTOPERATOR_COMMIT/testoperator ./testoperator
          sudo chmod +x ./testoperator
          echo "TESTOPERATOR_DOWNLOADED=true" >> $GITHUB_ENV
        else
          echo "TESTOPERATOR_DOWNLOADED=false" >> $GITHUB_ENV
        fi
    
    - name: Setup Rust
      if: ${{ env.TESTOPERATOR_DOWNLOADED != 'true' }}
      uses: spiceai/spiceai/.github/actions/setup-rust@trunk
      with:
        os: 'linux'

    - name: Setup cc
      if: ${{ env.TESTOPERATOR_DOWNLOADED != 'true' && inputs.target_os == 'linux' }}
      uses: spiceai/spiceai/.github/actions/setup-cc@trunk

    - name: Build the testoperator if it wasn't downloaded
      shell: bash
      if: ${{ env.TESTOPERATOR_DOWNLOADED != 'true' }}
      run: |
        cargo build -p testoperator --release
        cp target/release/testoperator ./testoperator
        chmod +x ./testoperator
      
    - name: Upload the testoperator binary
      shell: bash
      if: ${{ env.TESTOPERATOR_DOWNLOADED != 'true' }}
      run: |
        mc cp ./testoperator spice-minio/artifacts/testoperator/$TARGET_BINARY/$TESTOPERATOR_COMMIT/testoperator